# Generated by Django 3.1.3 on 2020-11-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Alias de la imagen', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en Dolares', max_digits=30)),
                ('pricebs', models.DecimalField(decimal_places=2, default=1, help_text='Precion en Bolivares', max_digits=30)),
                ('description', models.CharField(help_text='Descripcion del producto', max_length=200)),
                ('name_image', models.CharField(help_text='Debes colocar el nombre de la imagen con la extension por ejemplo: imagen.png ', max_length=50)),
                ('picture', models.ImageField(upload_to='imagesp')),
                ('cant', models.PositiveSmallIntegerField(default=1, help_text='Cantidad disponible el producto en el almacen')),
                ('visible', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre', max_length=1000)),
                ('cantshopping', models.PositiveSmallIntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='procesos.product')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
