# Generated by Django 3.1.3 on 2020-11-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_auto_20201123_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='cantshopping',
            new_name='cantidad',
        ),
    ]
