# Generated by Django 3.1.3 on 2020-11-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_auto_20201123_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='product',
        ),
        migrations.AddField(
            model_name='shopping',
            name='product',
            field=models.ManyToManyField(related_name='user_products', to='procesos.Product'),
        ),
    ]
