# Generated by Django 3.1.3 on 2020-11-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_auto_20201123_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='shopping',
            name='cantidad',
            field=models.ManyToManyField(related_name='cantidad_products', to='procesos.Product'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='product',
            field=models.ManyToManyField(related_name='seleccion_products', to='procesos.Product'),
        ),
    ]
