# Generated by Django 3.1.3 on 2020-11-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0005_auto_20201123_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='shopping',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
