# Generated by Django 3.1.3 on 2020-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_auto_20201123_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='monto',
            field=models.CharField(default=str, help_text='Precio de la venta en $', max_length=1000),
            preserve_default=False,
        ),
    ]
