# Generated by Django 3.1.3 on 2020-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0008_shopping_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='cantidad',
            field=models.CharField(default=0, help_text='cantidad por producto', max_length=500),
        ),
    ]
