# Generated by Django 3.1.3 on 2020-11-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0009_auto_20201123_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='cantidad',
            field=models.CharField(default=0, help_text='cantidad por producto separado por coma', max_length=500),
        ),
    ]
