# Generated by Django 3.1.3 on 2020-11-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0010_auto_20201123_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopping',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
